INSERT INTO techtrek_db.users
    (id,
     bio_summary,
     create_date,
     email,
     employment_status,
     first_name,
     github_username,
     last_name,
     linkedin_username,
     modify_date,
     user_password,
     phone_number,
     cohort_id,
     role_id)

VALUES (1,
        'Hello it me',
        '2020-05-21 00:00:00.000000',
        'danielle.tobler210@gmail.com',
        true,
        'Danielle',
        'dmtobler',
        'Tobler',
        'danielle-tobler',
        null,
        'test',
        '2102322232',
        1,
        3);